name: 3dct
dependencies:
- cairo=1.12.18=6
- cycler=0.10.0=py27_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- glib=2.43.0=1
- harfbuzz=0.9.39=1
- https://conda.binstar.org/menpo::opencv=2.4.11=nppy27_0
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.3=0
- numpy=1.11.1=py27_0
- openssl=1.0.2h=1
- pango=1.39.0=1
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- pycairo=1.10.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.18.0=np111py27_0
- setuptools=26.1.1=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - colorama==0.3.7
  - qimage2ndarray==1.6
  - tifffile==0.9.2
prefix: /home/jan/anaconda3/envs/3dct

